/*
 * iwOS
 *
 * API for iwOS food delivery & ticketing
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: info@iwos.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EventOutput : IEquatable<EventOutput>
    { 
        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [Required]
        [DataMember(Name="product")]
        public Product Product { get; set; }

        /// <summary>
        /// Gets or Sets Stock
        /// </summary>
        [Required]
        [DataMember(Name="stock")]
        public int? Stock { get; set; }

        /// <summary>
        /// Gets or Sets Assistants
        /// </summary>
        [Required]
        [DataMember(Name="assistants")]
        public List<Assistant> Assistants { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventOutput {\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  Stock: ").Append(Stock).Append("\n");
            sb.Append("  Assistants: ").Append(Assistants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EventOutput)obj);
        }

        /// <summary>
        /// Returns true if EventOutput instances are equal
        /// </summary>
        /// <param name="other">Instance of EventOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventOutput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Product == other.Product ||
                    Product != null &&
                    Product.Equals(other.Product)
                ) && 
                (
                    Stock == other.Stock ||
                    Stock != null &&
                    Stock.Equals(other.Stock)
                ) && 
                (
                    Assistants == other.Assistants ||
                    Assistants != null &&
                    Assistants.SequenceEqual(other.Assistants)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Product != null)
                    hashCode = hashCode * 59 + Product.GetHashCode();
                    if (Stock != null)
                    hashCode = hashCode * 59 + Stock.GetHashCode();
                    if (Assistants != null)
                    hashCode = hashCode * 59 + Assistants.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EventOutput left, EventOutput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EventOutput left, EventOutput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
