/*
 * iwOS
 *
 * API for iwOS food delivery & ticketing
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: info@iwos.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EventsInput : IEquatable<EventsInput>
    { 
        /// <summary>
        /// Gets or Sets MinDate
        /// </summary>
        [DataMember(Name="min_date")]
        public string MinDate { get; set; }

        /// <summary>
        /// Gets or Sets MaxDate
        /// </summary>
        [DataMember(Name="max_date")]
        public string MaxDate { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name="language")]
        public string Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventsInput {\n");
            sb.Append("  MinDate: ").Append(MinDate).Append("\n");
            sb.Append("  MaxDate: ").Append(MaxDate).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EventsInput)obj);
        }

        /// <summary>
        /// Returns true if EventsInput instances are equal
        /// </summary>
        /// <param name="other">Instance of EventsInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventsInput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MinDate == other.MinDate ||
                    MinDate != null &&
                    MinDate.Equals(other.MinDate)
                ) && 
                (
                    MaxDate == other.MaxDate ||
                    MaxDate != null &&
                    MaxDate.Equals(other.MaxDate)
                ) && 
                (
                    Language == other.Language ||
                    Language != null &&
                    Language.Equals(other.Language)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MinDate != null)
                    hashCode = hashCode * 59 + MinDate.GetHashCode();
                    if (MaxDate != null)
                    hashCode = hashCode * 59 + MaxDate.GetHashCode();
                    if (Language != null)
                    hashCode = hashCode * 59 + Language.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EventsInput left, EventsInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EventsInput left, EventsInput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
