/*
 * iwOS
 *
 * API for iwOS food delivery & ticketing
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: info@iwos.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TicketInputSecret : IEquatable<TicketInputSecret>
    { 
        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [Required]
        [DataMember(Name="secret")]
        public string Secret { get; set; }

        /// <summary>
        /// Gets or Sets OnlyRead
        /// </summary>
        [DataMember(Name="only_read")]
        public int? OnlyRead { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TicketInputSecret {\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  OnlyRead: ").Append(OnlyRead).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TicketInputSecret)obj);
        }

        /// <summary>
        /// Returns true if TicketInputSecret instances are equal
        /// </summary>
        /// <param name="other">Instance of TicketInputSecret to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TicketInputSecret other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Secret == other.Secret ||
                    Secret != null &&
                    Secret.Equals(other.Secret)
                ) && 
                (
                    OnlyRead == other.OnlyRead ||
                    OnlyRead != null &&
                    OnlyRead.Equals(other.OnlyRead)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Secret != null)
                    hashCode = hashCode * 59 + Secret.GetHashCode();
                    if (OnlyRead != null)
                    hashCode = hashCode * 59 + OnlyRead.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TicketInputSecret left, TicketInputSecret right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TicketInputSecret left, TicketInputSecret right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
