/*
 * iwOS
 *
 * API for iwOS food delivery & ticketing
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: info@iwos.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TicketInputData : IEquatable<TicketInputData>
    { 
        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [Required]
        [DataMember(Name="order_id")]
        public int? OrderId { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [Required]
        [DataMember(Name="product_id")]
        public int? ProductId { get; set; }

        /// <summary>
        /// Gets or Sets ScheduleId
        /// </summary>
        [Required]
        [DataMember(Name="schedule_id")]
        public int? ScheduleId { get; set; }

        /// <summary>
        /// Gets or Sets OnlyRead
        /// </summary>
        [DataMember(Name="only_read")]
        public int? OnlyRead { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TicketInputData {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  ScheduleId: ").Append(ScheduleId).Append("\n");
            sb.Append("  OnlyRead: ").Append(OnlyRead).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TicketInputData)obj);
        }

        /// <summary>
        /// Returns true if TicketInputData instances are equal
        /// </summary>
        /// <param name="other">Instance of TicketInputData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TicketInputData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OrderId == other.OrderId ||
                    OrderId != null &&
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    ProductId == other.ProductId ||
                    ProductId != null &&
                    ProductId.Equals(other.ProductId)
                ) && 
                (
                    ScheduleId == other.ScheduleId ||
                    ScheduleId != null &&
                    ScheduleId.Equals(other.ScheduleId)
                ) && 
                (
                    OnlyRead == other.OnlyRead ||
                    OnlyRead != null &&
                    OnlyRead.Equals(other.OnlyRead)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OrderId != null)
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    if (ProductId != null)
                    hashCode = hashCode * 59 + ProductId.GetHashCode();
                    if (ScheduleId != null)
                    hashCode = hashCode * 59 + ScheduleId.GetHashCode();
                    if (OnlyRead != null)
                    hashCode = hashCode * 59 + OnlyRead.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TicketInputData left, TicketInputData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TicketInputData left, TicketInputData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
